version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: questionnaire-postgres
    restart: always
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ../backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - questionnaire-network

networks:
  questionnaire-network:
    driver: bridge
